### ISSUE TITLE
Build warning

### ISSUE THREAD

**Issue by xclid** [azerothcore/mod-skip-dk-starting-area#11]
https://github.com/azerothcore/azerothcore-wotlk/commit/0b02ba87fc60d538b78a401604eb8955b895515f

`/root/azerothcore/modules/mod-skip-dk-starting-area/src/SkipDK.cpp:32:25: warning: 'GetBoolDefault' is deprecated: Use GetOption<bool> instead [-Wdeprecated-declarations]
        if (sConfigMgr->GetBoolDefault("Skip.Deathknight.Starter.Announce.enable", true))
                        ^
/root/azerothcore/src/common/Configuration/Config.h:57:7: note: 'GetBoolDefault' has been explicitly marked deprecated here
    [[deprecated("Use GetOption<bool> instead")]]
      ^
/root/azerothcore/modules/mod-skip-dk-starting-area/src/SkipDK.cpp:46:31: warning: 'GetFloatDefault' is deprecated: Use GetOption<float> instead [-Wdeprecated-declarations]
        int DKL = sConfigMgr->GetFloatDefault("Skip.Deathknight.Start.Level", 58);
                              ^
/root/azerothcore/src/common/Configuration/Config.h:63:7: note: 'GetFloatDefault' has been explicitly marked deprecated here
    [[deprecated("Use GetOption<float> instead")]]
      ^
/root/azerothcore/modules/mod-skip-dk-starting-area/src/SkipDK.cpp:48:25: warning: 'GetBoolDefault' is deprecated: Use GetOption<bool> instead [-Wdeprecated-declarations]
        if (sConfigMgr->GetBoolDefault("Skip.Deathknight.Starter.Enable", true))
                        ^
/root/azerothcore/src/common/Configuration/Config.h:57:7: note: 'GetBoolDefault' has been explicitly marked deprecated here
    [[deprecated("Use GetOption<bool> instead")]]
      ^
/root/azerothcore/modules/mod-skip-dk-starting-area/src/SkipDK.cpp:104:25: warning: 'GetBoolDefault' is deprecated: Use GetOption<bool> instead [-Wdeprecated-declarations]
        if (sConfigMgr->GetBoolDefault("GM.Skip.Deathknight.Starter.Enable", true))
                        ^
/root/azerothcore/src/common/Configuration/Config.h:57:7: note: 'GetBoolDefault' has been explicitly marked deprecated here
    [[deprecated("Use GetOption<bool> instead")]]
      ^
/root/azerothcore/modules/mod-skip-dk-starting-area/src/SkipDK.cpp:184:29: warning: 'GetBoolDefault' is deprecated: Use GetOption<bool> instead [-Wdeprecated-declarations]
            if (sConfigMgr->GetBoolDefault("Skip.Deathknight.Optional.Enable", true))
                            ^
/root/azerothcore/src/common/Configuration/Config.h:57:7: note: 'GetBoolDefault' has been explicitly marked deprecated here
    [[deprecated("Use GetOption<bool> instead")]]
      ^
/root/azerothcore/modules/mod-skip-dk-starting-area/src/SkipDK.cpp:209:35: warning: 'GetFloatDefault' is deprecated: Use GetOption<float> instead [-Wdeprecated-declarations]
            int DKL = sConfigMgr->GetFloatDefault("Skip.Deathknight.Start.Level", 58);
                                  ^
/root/azerothcore/src/common/Configuration/Config.h:63:7: note: 'GetFloatDefault' has been explicitly marked deprecated here
    [[deprecated("Use GetOption<float> instead")]]
      ^
`

**Comment by acidmanifesto** [comment]
fixed. Thank you for the information.

**Comment by xclid** [comment]
My pleasure
