### ISSUE TITLE
Incorrect tag for showing up on the website catalog

### ISSUE THREAD

**Issue by gregflynn** [azerothcore/mod-skip-dk-starting-area#15]
missing a z

**Comment by acidmanifesto** [comment]
Can u give me a link to it in the catalog?

**Comment by acidmanifesto** [comment]
Ah ok. So i was just informed its the tags. ![unknown-367.png](https://user-images.githubusercontent.com/16887899/165373187-c31a6371-7c22-42c7-a5e6-5926de711ddc.png)
@Helias are u able to correct it? The z is missing in azerothcore which is supposively causing issues with it not showing in the catalog

**Comment by Helias** [comment]
fixed, clear your cache or use an incognito browser to see it in the catalogue
