### ISSUE TITLE
Error in the end of compling

### ISSUE THREAD

**Issue by loveofmaria** [azerothcore/mod-skip-dk-starting-area#17]
[ 99%] Building CXX object src/server/apps/CMakeFiles/worldserver.dir/worldserver/ACSoap/ACSoap.cpp.o
[ 99%] Building CXX object src/server/apps/CMakeFiles/worldserver.dir/worldserver/CommandLine/CliRunnable.cpp.o
[ 99%] Building CXX object src/server/apps/CMakeFiles/worldserver.dir/worldserver/RemoteAccess/RASession.cpp.o
[100%] Linking CXX executable worldserver
/usr/bin/ld: ../../../modules/libmodules.a(ModulesLoader.cpp.o): in function `AddModulesScripts()':
/home/gudan/AzerothCore-wotlk-with-NPCBots/build/modules/gen_scriptloader/static/ModulesLoader.cpp:53: undefined reference to `Addmod_skip_dk_starting_area_masterScripts()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/server/apps/CMakeFiles/worldserver.dir/build.make:194: src/server/apps/worldserver] Error 1
make[1]: *** [CMakeFiles/Makefile2:1105: src/server/apps/CMakeFiles/worldserver.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

**Comment by acidmanifesto** [comment]
Remove master from the module folder name.
