### ISSUE TITLE
getLevel deprecated

### ISSUE THREAD

**Issue by robcasey** [azerothcore/mod-skip-dk-starting-area#21]
It seems that `getLevel()` was removed in this upstream commit:
https://github.com/azerothcore/azerothcore-wotlk/commit/21f86d1c3c0d48ca8f31c6d6f29005fe492a9a2e

Changing it to `GetLevel()` will probably resolve the issue but I have not tried it.

https://github.com/azerothcore/mod-skip-dk-starting-area/blob/463e9af64f8fa88a276fd241d6fa7c1f301c636b/src/SkipDK.cpp#L113

**Comment by biosfree** [comment]
I tried to replace the following following compiler's advice
`if (player->getLevel() <= DKL)`
by
`if (player->GetLevel() <= DKL)`

After that it compiled without errors and was successfully tested

**Comment by gruberchris** [comment]
I can second validating this is an actual bug and the fix @biosfree offered here.
